ui_settings:
  llm_base_url: http://localhost:8000/v1
  llm_model: qwen3-4b-awq
  llm_api_key: ''
  temperature: 0.2
  embedding_base_url: http://localhost:8001/v1
  embedding_model: bge-m3
  embedding_api_key: ''
  embedding_dimensions: 1024
  embedding_batch_size: 16
  max_tokens: 8000
  streaming_max_tokens: 8000
  rephrasing_max_tokens: 4000
  max_citations: 3
  require_quotes: true
  quote_max_words: 12
  chroma_host: localhost
  chroma_port: 8100
  final_passages: 8
  cosine_floor: 0.05
  min_keyword_overlap: 4
  dense_k: 80
  lexical_k: 80
  rrf_k: 60
  mmr_lambda: 0.5
  routing_threshold: 0.35
  routing_sample_size: 20
  use_reranker: true
  allow_reranker_fallback: true
  reranker_url: http://localhost:8002/rerank
  reranker_port: 8002
  reranker_timeout: 8
  reranker_pool_size_multiplier: 3
  reranker_score_weight: 0.7
  embedding_cache_enabled: true
  embedding_cache_max_items: 512
  embedding_cache_ttl_seconds: 600
  chunk_size_tokens: 250
  chunk_stride_tokens: 75
  max_html_chars: 500000
  drop_boilerplate: true
  drop_labels:
  - template
  - archive
  - index
  dedup_enabled: true
  dedup_method: minhash
  dedup_threshold: 0.92
  fuzzy_partial_ratio_min: 70
  log_level: DEBUG
  max_memory_messages: 8
  metrics_enabled: true
